language: node_js
node_js:
  - "node"
before_script:
  - "npm run build"
  - "npm test"
deploy:
  provider: lambda
  function_name: "StreamOnAlexaSkill-$TRAVIS_BRANCH"
  role: "arn:aws:iam::818032293643:role/service-role/node"
  module_name: "lambda/LambdaService"
  handler_name: "handle"
  zip: "src/main/typescript"
  region: "eu-west-1"
  runtime: "nodejs4.3"
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  on:
    all_branches: true
    tags: false